### PR TITLE
Fix file 2nd load on drop-zone

### LINKED ISSUE #165: Import page doesn't refresh when a new file is loaded

### PR DESCRIPTION
**Pull request by tokland**
### :pushpin: References

* **Issue:** Closes #165

### :memo: Implementation

- Removed `@cache` on `readCell.` We'll review with @SferaDev whether to re-instate it somehow or remove it altogether.

### CODE REVIEW

File: src/data/ExcelPopulateRepository.ts [hunk 1]
```diff
@@ -106,7 +105,7 @@ export class ExcelPopulateRepository extends ExcelRepository {
         }
     }
 
-    @cache()
+    // @cache()
```
Comment (SferaDev) [inline src/data/ExcelPopulateRepository.ts:108]:
```suggestion
```

**Review by SferaDev — APPROVED** [review]

**Comment by SferaDev** [comment]
LGTM, merging into ``fix/review-nhwa-modules`` to further test it on the same branch
